FROM mcr.microsoft.com/devcontainers/universal:2

# Vue CLI is installed in postCreateCommand
# Flask is installed in postCreateCommand
# No need to install Node manually (handled by devcontainer feature)
